[package]
name = "archlinuxcn-packages"
version = "0.2.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.3"
ansi-to-html = "0.1.0"
anyhow = "1.0.53"
bigdecimal = "0.3.0"
cached = "0.30.0"
chrono = "0.4.19"
deadpool-postgres = "0.10.1"
enum-display-derive = "0.1.1"
openssl = { version = "0.10.38", features = ["vendored"] }
pg_bigdecimal = "0.1.4"
postgres-types = { version = "0.2.2", features = ["derive"]}
sentry = "0.24.2"
sentry-actix = "0.24.2"
serde = { version = "1.0.136", features = ["derive"] }
tokio-postgres = { version = "0.7.5", features = ["with-chrono-0_4"]}
yaml-rust = "0.4.5"
